### ISSUE TITLE
Part 2, A pairwise correlation example

### ISSUE THREAD

**Issue by Djafar1985** [hgeorgako/rfortraders#3]
Hi, Harry ! How are your quantitative feeling? =)
I have a question about the content, as a young Quantic .
On page 37 you mention about the csv file, but you have not created it , where you get information ? You have described the basic operation assignment , vectors , lists , matrices and data structures , but why you omitted the issue of export summary data in the form as described on page 38? 

I need to help!

**Comment by Djafar1985** [comment]
What is this?

extract_prices <- function(filtered_symbols, file_path = rfortraders / Chapter_02 / prices.csv) {
all_prices <- read.csv(file = file_path, header = TRUE, stringsAsFactors = FALSE)
rownames(all_prices) <- all_prices$Date
all_prices$Date <- NULL
valid_columns <- colnames(all_prices) %in% filtered_symbols
return(all_prices[, valid_columns])
}
extract_prices

result

> extract_prices
> function(filtered_symbols, file_path = rfortraders / Chapter_02 / prices.csv) {
> all_prices <- read.csv(file = file_path, header = TRUE, stringsAsFactors = FALSE)
> rownames(all_prices) <- all_prices$Date
> all_prices$Date <- NULL
> valid_columns <- colnames(all_prices) %in% filtered_symbols
> return(all_prices[, valid_columns])
> }

**Comment by Djafar1985** [comment]
кое что нашёл
http://stackoverflow.com/questions/14441729/read-a-csv-from-github-into-r

urlfile <- 'https://raw.githubusercontent.com/hgeorgako/rfortraders/master/Chapter_02/prices.csv' 
dsin <- read.csv ( urlfile, getOption("max.print"))

проблема в ограничении 1000 строк
[ reached getOption("max.print") -- omitted 856 rows ]

**Comment by hgeorgako** [comment]
Hopefully you already got this to work.  The file you need is here: https://github.com/hgeorgako/rfortraders/blob/master/Chapter_02/prices.csv  
The fastest way to get this is to download the file to your local computer and then use read.csv(file = "path on your local machine") to read in the data.  Another useful package that I use all the time to read in .csv files is "readr".  Once you install it, you can say:  readr::read_csv(filepath)

**Comment by Djafar1985** [comment]
Oh Harry , I'm really glad you answered my Problems!
I thought that you rarely come here and have grieved . 
I figured out how to load data into R from the site , but why limit of 1000 lines.
I will try your method !
Thanks for the answer!
